const $p = {
    set: ($control, val) => { },
    apiGet: getRequest,
    apiCreate: createRequest,
    apiUpdate: updateRequest,
    apiDelete: deleteRequest,
    apiUsersGet: usersGetRequest,
    apiUsersCreate: usersCreateRequest,
    apiUsersUpdate: usersUpdateRequest,
    apiUsersDelete: usersDeleteRequest,
    apiSendMail: sendMailRequest,
    id: () => { },
    send: data => { },
    siteId: () => { },
    getColumnName: name => { },
    getControl: labelName => { },
    getField: labelName => { },
    clearMessage: () => { },
    setMessage: (target, value) => { },
    loginId: () => { },
    userId: () => { },
    userName: () => { },
    referenceType: () => { },
    getGridCell: (id, name) => { },
    getGridColumnIndex: name => { },
    getGridRow: id => { },
    before_validate_Create: () => { },
    before_validate_Update: () => { },
    before_validate_Delete: () => { },
    after_validate_Create: () => { },
    after_validate_Update: () => { },
    after_validate_Delete: () => { },
    before_send_Create: () => { },
    before_send_Update: () => { },
    before_send_Delete: () => { },
    after_send_Create: () => { },
    after_send_Update: () => { },
    after_send_Delete: () => { },
    before_set_Create: () => { },
    before_set_Update: () => { },
    before_set_Delete: () => { },
    after_set_Create: () => { },
    after_set_Update: () => { },
    after_set_Delete: () => { },
    after_set_GridRows: () => { },
    on_editor_load: () => { },
    on_grid_load: () => { },
}

const getRequest = ({
    async = true,
    id,
    data = dataOfGetRequest,
    done = (data = getResponseData) => { },
    fail = data => { },
    always = data => { }
}) => { };

const createRequest = ({
    async = true,
    id,
    data = dataOfCreateAndUpdateRequest,
    done = data => { },
    fail = data => { },
    always = data => { }
}) => { };

const updateRequest = ({
    async = true,
    id,
    data = dataOfCreateAndUpdateRequest,
    done = data => { },
    fail = data => { },
    always = data => { }
}) => { };

const deleteRequest = ({
    async = true,
    id,
    data = dataOfBaseRequest,
    done = data => { },
    fail = data => { },
    always = data => { }
}) => { };

const usersGetRequest = ({
    async = true,
    data = dataOfUsersGetRequest,
    done = (data = getResponseData) => { },
    fail = data => { },
    always = data => { }
}) => { };

const usersCreateRequest = ({
    async = true,
    data = dataOfUsersCreateAndUpdateRequest,
    done = data => { },
    fail = data => { },
    always = data => { }
}) => { };

const usersUpdateRequest = ({
    async = true,
    id,
    data = dataOfUsersCreateAndUpdateRequest,
    done = data => { },
    fail = data => { },
    always = data => { }
}) => { };

const usersDeleteRequest = ({
    async = true,
    id,
    data = dataOfBaseRequest,
    done = data => { },
    fail = data => { },
    always = data => { }
}) => { };

const sendMailRequest = ({
    async = true,
    id,
    data = dataOfSendMailRequest,
    done = data => { },
    fail = data => { },
    always = data => { }
}) => { };

const dataOfBaseRequest = {
    ApiVersion : 1.1,
    ApiKey: ""
}

const dataOfGetRequest = {
    ApiVersion : 1.1,
    ApiKey: "",
    View : ViewItems
}

const dataOfUsersGetRequest = {
    ApiVersion : 1.1,
    ApiKey: "",
    View : ViewUsers
}

const dataOfCreateAndUpdateRequest = {
    ApiVersion : 1.1,
    ApiKey: "",
    ClassHash : Class,
    NumHash : Num,
    DateHash : Date,
    DescriptionHash : Description,
    CheckHash : Check
}

const dataOfUsersCreateAndUpdateRequest = {
    ApiVersion : 1.1,
    ApiKey: "",
    UserId,
    Ver,
    LoginId,
    Name,
    UserCode,
    Birthday,
    Gender,
    Language,
    TimeZone,
    DeptCode,
    Body,
    LastLoginTime,
    PasswordExpirationTime,
    PasswordChangeTime,
    NumberOfLogins,
    NumberOfDenial,
    TenantManager,
    Disabled,
    Lockout,
    LockoutCounter,
    Comments,
    Creator,
    Updator,
    CreatedTime,
    UpdatedTime
}

const dataOfSendMailRequest = {
    ApiVersion : 1.1,
    ApiKey: "",
    From,
    To,
    Cc,
    Bcc,
    Title,
    Body
}

const ViewItems = {
    ColumnFilterHash : ColumnFilterHashItems,
    ColumnSorterHash
}

const ViewUsers = {
    ColumnFilterHash : ColumnFilterHashUsers,
    ColumnSorterHash
}

const ColumnFilterHashItems = {
    SiteId,
    IssueId,
    ResultId,
    Body,
    StartTime,
    CompletionTime,
    WorkValue,
    ProgressRate,
    RemainingWorkValue,
    UpdateTime,
    Ver,
    Title,
    Status,
    Manager,
    Owner,
    Comments,
    Creator,
    Updator,
    CreatedTime,
    ItemTitle,
    ClassA,
    ClassB,
    ClassC,
    ClassD,
    ClassE,
    ClassF,
    ClassG,
    ClassH,
    ClassI,
    ClassJ,
    ClassK,
    ClassL,
    ClassM,
    ClassN,
    ClassO,
    ClassP,
    ClassQ,
    ClassR,
    ClassS,
    ClassT,
    ClassU,
    ClassV,
    ClassW,
    ClassX,
    ClassY,
    ClassZ,
    NumA,
    NumB,
    NumC,
    NumD,
    NumE,
    NumF,
    NumG,
    NumH,
    NumI,
    NumJ,
    NumK,
    NumL,
    NumM,
    NumN,
    NumO,
    NumP,
    NumQ,
    NumR,
    NumS,
    NumT,
    NumU,
    NumV,
    NumW,
    NumX,
    NumY,
    NumZ,
    DateA,
    DateB,
    DateC,
    DateD,
    DateE,
    DateF,
    DateG,
    DateH,
    DateI,
    DateJ,
    DateK,
    DateL,
    DateM,
    DateN,
    DateO,
    DateP,
    DateQ,
    DateR,
    DateS,
    DateT,
    DateU,
    DateV,
    DateW,
    DateX,
    DateY,
    DateZ,
    DescriptionA,
    DescriptionB,
    DescriptionC,
    DescriptionD,
    DescriptionE,
    DescriptionF,
    DescriptionG,
    DescriptionH,
    DescriptionI,
    DescriptionJ,
    DescriptionK,
    DescriptionL,
    DescriptionM,
    DescriptionN,
    DescriptionO,
    DescriptionP,
    DescriptionQ,
    DescriptionR,
    DescriptionS,
    DescriptionT,
    DescriptionU,
    DescriptionV,
    DescriptionW,
    DescriptionX,
    DescriptionY,
    DescriptionZ,
    CheckA,
    CheckB,
    CheckC,
    CheckD,
    CheckE,
    CheckF,
    CheckG,
    CheckH,
    CheckI,
    CheckJ,
    CheckK,
    CheckL,
    CheckM,
    CheckN,
    CheckO,
    CheckP,
    CheckQ,
    CheckR,
    CheckS,
    CheckT,
    CheckU,
    CheckV,
    CheckW,
    CheckX,
    CheckY,
    CheckZ,
    CheckA,
    CheckB,
    CheckC,
    CheckD,
    CheckE,
    CheckF,
    CheckG,
    CheckH,
    CheckI,
    CheckJ,
    CheckK,
    CheckL,
    CheckM,
    CheckN,
    CheckO,
    CheckP,
    CheckQ,
    CheckR,
    CheckS,
    CheckT,
    CheckU,
    CheckV,
    CheckW,
    CheckX,
    CheckY,
    CheckZ
}

const ColumnFilterHashUsers = {
    UserId,
    Ver,
    LoginId,
    Name,
    UserCode,
    Birthday,
    Gender,
    Language,
    TimeZone,
    DeptCode,
    Body,
    LastLoginTime,
    PasswordExpirationTime,
    PasswordChangeTime,
    NumberOfLogins,
    NumberOfDenial,
    TenantManager,
    Disabled,
    Lockout,
    LockoutCounter,
    Comments,
    Creator,
    Updator,
    CreatedTime,
    UpdatedTime
}

const getResponseData = {
    StatusCode,
    Response = Response,
};

const Response = {
    Offset,
    PageSize,
    TotalCount,
    Data : {
        ClassHash : Class,
        NumHash : Num,
        DateHash : Date,
        DescriptionHash : Description,
        CheckHash : Check
    }
};

const Class = {
    ClassA,
    ClassB,
    ClassC,
    ClassD,
    ClassE,
    ClassF,
    ClassG,
    ClassH,
    ClassI,
    ClassJ,
    ClassK,
    ClassL,
    ClassM,
    ClassN,
    ClassO,
    ClassP,
    ClassQ,
    ClassR,
    ClassS,
    ClassT,
    ClassU,
    ClassV,
    ClassW,
    ClassX,
    ClassY,
    ClassZ
}

const Num = {
    NumA,
    NumB,
    NumC,
    NumD,
    NumE,
    NumF,
    NumG,
    NumH,
    NumI,
    NumJ,
    NumK,
    NumL,
    NumM,
    NumN,
    NumO,
    NumP,
    NumQ,
    NumR,
    NumS,
    NumT,
    NumU,
    NumV,
    NumW,
    NumX,
    NumY,
    NumZ
}

const Date = {
    DateA,
    DateB,
    DateC,
    DateD,
    DateE,
    DateF,
    DateG,
    DateH,
    DateI,
    DateJ,
    DateK,
    DateL,
    DateM,
    DateN,
    DateO,
    DateP,
    DateQ,
    DateR,
    DateS,
    DateT,
    DateU,
    DateV,
    DateW,
    DateX,
    DateY,
    DateZ
}

const Description = {
    DescriptionA,
    DescriptionB,
    DescriptionC,
    DescriptionD,
    DescriptionE,
    DescriptionF,
    DescriptionG,
    DescriptionH,
    DescriptionI,
    DescriptionJ,
    DescriptionK,
    DescriptionL,
    DescriptionM,
    DescriptionN,
    DescriptionO,
    DescriptionP,
    DescriptionQ,
    DescriptionR,
    DescriptionS,
    DescriptionT,
    DescriptionU,
    DescriptionV,
    DescriptionW,
    DescriptionX,
    DescriptionY,
    DescriptionZ
}

const Check = {
    CheckA,
    CheckB,
    CheckC,
    CheckD,
    CheckE,
    CheckF,
    CheckG,
    CheckH,
    CheckI,
    CheckJ,
    CheckK,
    CheckL,
    CheckM,
    CheckN,
    CheckO,
    CheckP,
    CheckQ,
    CheckR,
    CheckS,
    CheckT,
    CheckU,
    CheckV,
    CheckW,
    CheckX,
    CheckY,
    CheckZ
}


module.exports = $p